### ISSUE TITLE
Bash version is too old (macOS)

### ISSUE THREAD

**Issue by Tony-Sol** [whame/tmux-modal#11]
```
ERROR: Bash version is too old. Please upgrade to version 4.0 or newer
```

**Comment by whame** [comment]
You can use tmux-modal with zsh (I do that myself). This is print is telling you that your _`bash`_  is too old (not your zsh). What bash version do you have? (run `bash --version` and also see https://github.com/whame/tmux-modal/issues/9)

**Comment by Tony-Sol** [comment]
I don't use bash, i use zsh, so `BASH_VERSINFO` is not set

**Comment by whame** [comment]
Oh, so you are saying that you don't even have bash installed at all? I'll guess that is a requirement for tmux-modal then.

**Comment by Tony-Sol** [comment]
No, bash itself is installed, but not used at all.
So thats why there are no bash-specific envs set.

It's default for macos so far, use zsh instead of bash
