### ISSUE TITLE
Allow getting out of "modal mode" by pressing `ESC`

### ISSUE THREAD

**Issue by farzadmf** [whame/tmux-modal#3]
Currently, the only. way to get out of "modal mode" is the press `M-m` again. It would be nice to also allow `ESC` to achieve the same thing

**Comment by whame** [comment]
So we could maybe add an extra configurable "exit" keybinding, i.e. `M-m` behaves as usual enter/exit but one extra key can be set to also exit (e.g. `ESC`, `i` or whatever).

I'll work on this soon. Please stand-by!

**Comment by farzadmf** [comment]
Nice! Could it be somehow "appending" the key? Basically, allow exiting out by pressing _either_ `ESC` or `M-m`?

**Comment by whame** [comment]
I believe it should be consistent, i.e. one keybinding does _one_ thing. If we have several ways of doing the same thing, it would get confusing (e.g. "do I need to override _two_ variables for the same thing"). It's easier to learn one thing and stick to it :)

**Comment by farzadmf** [comment]
Sure, of course whatever I say is only suggestion, you're the one making the final decision 🙂

And I guess we can close this now?
