### ISSUE TITLE
Not able to enter modal mode

### ISSUE THREAD

**Issue by dnguyenzd** [whame/tmux-modal#9]
I tried installing using `tpm`, and I can see `tmux-modal` folder in `~/.tmux/plugins`, however `M-m` doesn't do anything. Other plugins installed with `tpm` are working fine

When I do `tmux list-keys -T root`, it doesn't have any keys registered by `tmux-modal`

I also tried putting `run '~/.tmux/plugins/tmux-modal/tmux-modal.tmux'` at the end of my `.tmux.conf` file but it's not working either

**Comment by whame** [comment]
Hm, that's weird. Could you try to run tmux-modal.tmux in a tmux session manually? I.e. in tmux do

```
./tmux-modal.tmux
```

**Comment by dnguyenzd** [comment]
I got this error when executing it directly:

```
/tmux-modal.tmux: line 27: syntax error near unexpected token `&'
```

look like this is one of those special cases of `list-keys` that the script misses to handle. I attached here the output of `tmux list-keys` for reference

[tmux-list-keys.txt](https://github.com/whame/tmux-modal/files/9760147/tmux-list-keys.txt)

**Comment by whame** [comment]
Ah no, this is bash reporting a syntax error. I think you are using a too old bash version. Could you report what

```
bash --version
```

says? I'm guessing that you are using version older than 4.0. That syntax was introduced in bash 4.0 (which is more than 10 years ago...).

**Comment by dnguyenzd** [comment]
you are right, I'm using default bash version from MacOS, which is 3.2.57
using latest bash from brew fixes it

it might be worth mentioning bash version requirement as prerequisite though because as I know, Apple will not ship newer version of bash due to licensing, so a lot of people have version 3 by default

**Comment by whame** [comment]
Aha interesting! We would of course like MacOS users to use this plugin without any hassles. Maybe the switch-case can be rewritten to be portable?

For now, I'll add a check for bash version. Thank you!

**Comment by bradfordwagner** [comment]
@dnguyenzd - I was able to get this working on a mac. I ran to use the brew installed version of bash which refd bash 5.x
```brew link --overwrite bash```
